instruments_metainfo:
  type: single

instruments:
  Market: "MOEX"
  Active: "adjusted_stock"
  Timeframe: "1d"
  Name: "ABIO.MOEX"
  Start: "2023-08-18"
  End: "2026-07-08"

brokers:
  commissions: 0.0001
  slippage: 0.0

strategy:
  take_profit_percent: 0.05
  stop_loss_percent: 0.01

strategy_info:
  path: "strategies/demo_strategy.py"
  name: "DemoStrategy"

output:
  equity_plot: "equity.png"
  trades_csv: "trades_log.csv"
  orders_csv: "orders_log.csv"