instruments_metainfo:
  type: single

instruments:
  - Market: "MOEX"
    Active: "adjusted_stock"
    Timeframe: "1d"
    Name: "ABIO.MOEX"
    Start: "2023-08-18"
    End: "2026-07-08"

brokers:
  commissions: 0.0001
  slippage: 0.0

strategy_info:
  path: "strategies/ma_cross.py"
  name: "MA_cross"

output:
  equity_plot: "equity.png"
  trades_csv: "trades_log.csv"